language: node_js
node_js:
  - "0.12"

before_script:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install coveralls
  - npm install mockery

after_script:
  - npm run coveralls

deploy:
  provider: npm
  email: "kristopher.l.alexander@gmail.com"
  api_key: "YmluYXJ5YWxjaGVtaXN0OmJhcmRvY2slU1I3MQ=="
  on:
    tags: true